name: config-server
replicaCount: 1

image:
  repository: milfist/calculator-service
  tag: 1.0.0
containerPort: 8888
targetPort: 8888

namespace: terraform-helm-rancher-namespace

volume:
  mountPath: /test_logs
  name: test-logs
  hostPath: /mnt/test_logs
